#!/usr/bin/env bash
# install-run.sh — 一键克隆/更新并安装依赖，可选立即开跑
# 用法（服务器）：
#   bash <(curl -fsSL https://raw.githubusercontent.com/itbulu/LeBench/main/install-run.sh)
#   bash <(curl -fsSL https://raw.githubusercontent.com/itbulu/LeBench/main/install-run.sh) --run
#   bash <(curl -fsSL ...) --run-lite
set -euo pipefail

REPO_URL="${LZY_REPO_URL:-https://github.com/itbulu/LeBench.git}"
INSTALL_DIR="${LZY_INSTALL_DIR:-/opt/lzy-bench}"
DO_RUN=0
RUN_LITE=0

for arg in "$@"; do
  case "${arg}" in
    --run) DO_RUN=1 ;;
    --run-lite) DO_RUN=1; RUN_LITE=1 ;;
    --dir=*) INSTALL_DIR="${arg#*=}" ;;
    -h|--help)
      cat <<EOF
LZY Bench 一键安装

  bash install-run.sh              # 仅克隆/更新 + install.sh
  bash install-run.sh --run        # 安装后全量评测
  bash install-run.sh --run-lite   # 安装后精简评测（不含 docker/wordpress）
  bash install-run.sh --dir=/path  # 指定安装目录

环境变量：
  LZY_REPO_URL      默认 ${REPO_URL}
  LZY_INSTALL_DIR   默认 ${INSTALL_DIR}
EOF
      exit 0
      ;;
  esac
done

if [[ "$(id -u)" -ne 0 ]]; then
  echo "[ERROR] 请使用 root：sudo bash install-run.sh $*" >&2
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive
echo "[INFO] 确保 git / curl ..."
if command -v apt-get >/dev/null 2>&1; then
  apt-get update -y >/dev/null 2>&1 || true
  apt-get install -y git curl ca-certificates >/dev/null 2>&1 || apt-get install -y git curl ca-certificates
elif command -v dnf >/dev/null 2>&1; then
  dnf install -y git curl ca-certificates || true
elif command -v yum >/dev/null 2>&1; then
  yum install -y git curl ca-certificates || true
fi

if [[ -d "${INSTALL_DIR}/.git" ]]; then
  echo "[INFO] 更新已有仓库: ${INSTALL_DIR}"
  git -C "${INSTALL_DIR}" pull --ff-only origin main 2>/dev/null \
    || git -C "${INSTALL_DIR}" pull --ff-only 2>/dev/null \
    || echo "[WARN] git pull 失败，继续使用本地副本"
else
  echo "[INFO] 克隆 ${REPO_URL} → ${INSTALL_DIR}"
  mkdir -p "$(dirname "${INSTALL_DIR}")"
  if [[ -e "${INSTALL_DIR}" ]] && [[ ! -d "${INSTALL_DIR}/.git" ]]; then
    echo "[WARN] ${INSTALL_DIR} 已存在且非 git 仓库，直接使用"
  else
    git clone --depth 1 "${REPO_URL}" "${INSTALL_DIR}"
  fi
fi

cd "${INSTALL_DIR}"
chmod +x benchmark.sh install.sh install-run.sh 2>/dev/null || true
echo "[INFO] 安装评测依赖..."
./install.sh

echo ""
echo "[OK] 安装完成: ${INSTALL_DIR}"
echo "     命令: sudo ${INSTALL_DIR}/benchmark.sh"
echo "     或:   sudo lzy-bench"
echo "     文档: ${INSTALL_DIR}/platform/README.md"
echo "     对照: ${INSTALL_DIR}/docs/COMPARISON_ECS.md"

if [[ "${RUN_LITE}" -eq 1 ]]; then
  mkdir -p "${INSTALL_DIR}/config"
  cat >"${INSTALL_DIR}/config/local.conf" <<'EOF'
# generated by install-run.sh --run-lite
LZY_DEFAULT_MODULES="system cpu memory disk network route streaming ipquality"
EOF
  echo "[INFO] 已写入 config/local.conf（精简模块，含 ipquality）"
fi

if [[ "${DO_RUN}" -eq 1 ]]; then
  echo "[INFO] 开始评测..."
  exec ./benchmark.sh
fi
