#!/usr/bin/env bash
# core/report.sh - Markdown / HTML report generation

lzy_report_markdown() {
  local run_dir="${1:-${LZY_RUN_DIR}}"
  local run_id
  run_id="$(basename "${run_dir}")"
  local out_dir="${LZY_REPORTS_DIR}/${run_id}"
  local out="${out_dir}/report.md"

  if [[ ! -d "${run_dir}" ]]; then
    lzy_die "结果目录不存在: ${run_dir}"
  fi

  lzy_ensure_dir "${out_dir}"

  {
    echo "# ${LZY_NAME} 评测报告"
    echo ""
    echo "> 品牌：${LZY_BRAND}  |  版本：${LZY_VERSION}  |  Run ID：\`${run_id}\`"
    echo ""
    echo "生成时间：$(lzy_now_iso)"
    echo ""
    if [[ -f "${run_dir}/score.json" ]] && lzy_has_jq; then
      local overall
      overall="$(jq -r '.overall // "N/A"' "${run_dir}/score.json" 2>/dev/null || echo N/A)"
      echo "**综合评分：${overall} / 10**"
      echo ""
    fi
    echo "---"
    echo ""

    _lzy_report_section "系统信息" "${run_dir}/system.json"
    _lzy_report_section "CPU" "${run_dir}/cpu.json"
    _lzy_report_section "内存" "${run_dir}/memory.json"
    _lzy_report_section "磁盘" "${run_dir}/disk.json"
    _lzy_report_section "网络" "${run_dir}/network.json"
    _lzy_report_section "线路" "${run_dir}/route.json"
    _lzy_report_section "流媒体" "${run_dir}/streaming.json"
    _lzy_report_section "应用" "${run_dir}/application.json"
    _lzy_report_section "评分" "${run_dir}/score.json"

    echo "## 原始数据"
    echo ""
    echo "结果目录：\`${run_dir}\`"
    echo ""
    echo "---"
    echo ""
    echo "*Generated by ${LZY_NAME} (${LZY_BRAND}) — Once Test, Multiple Output*"
  } >"${out}"

  lzy_ok "Markdown 报告: ${out}"
  printf '%s\n' "${out}"
}

_lzy_report_section() {
  local title="$1"
  local file="$2"

  echo "## ${title}"
  echo ""
  if [[ ! -f "${file}" ]]; then
    echo "_未执行或无数据。_"
    echo ""
    return 0
  fi

  if lzy_has_jq; then
    echo '```json'
    jq '.' "${file}" 2>/dev/null || cat "${file}"
    echo '```'
  else
    echo '```json'
    cat "${file}"
    echo '```'
  fi
  echo ""
}

_lzy_html_escape() {
  local s="${1:-}"
  s="${s//&/&amp;}"
  s="${s//</&lt;}"
  s="${s//>/&gt;}"
  s="${s//\"/&quot;}"
  printf '%s' "${s}"
}

_lzy_html_metric_card() {
  local label="$1" value="$2"
  cat <<EOF
<div class="card">
  <div class="label">$(_lzy_html_escape "${label}")</div>
  <div class="value">$(_lzy_html_escape "${value}")</div>
</div>
EOF
}

_lzy_jq_or() {
  local file="$1" query="$2" fallback="${3:-—}"
  if [[ -f "${file}" ]] && lzy_has_jq; then
    local v
    v="$(jq -r "${query}" "${file}" 2>/dev/null || true)"
    if [[ -z "${v}" || "${v}" == "null" ]]; then
      printf '%s' "${fallback}"
    else
      printf '%s' "${v}"
    fi
  else
    printf '%s' "${fallback}"
  fi
}

lzy_report_html() {
  local run_dir="${1:-${LZY_RUN_DIR}}"
  local run_id
  run_id="$(basename "${run_dir}")"
  local out_dir="${LZY_REPORTS_DIR}/${run_id}"
  local out="${out_dir}/report.html"

  if [[ ! -d "${run_dir}" ]]; then
    lzy_die "结果目录不存在: ${run_dir}"
  fi
  lzy_ensure_dir "${out_dir}"

  local overall host os cpu_model
  overall="$(_lzy_jq_or "${run_dir}/score.json" '.overall' 'N/A')"
  host="$(_lzy_jq_or "${run_dir}/system.json" '.os.hostname' 'unknown')"
  os="$(_lzy_jq_or "${run_dir}/system.json" '.os.pretty_name')"
  cpu_model="$(_lzy_jq_or "${run_dir}/system.json" '.cpu.model')"

  local cpu_s mem_s disk_s net_s route_s app_s
  cpu_s="$(_lzy_jq_or "${run_dir}/score.json" '.scores.cpu')"
  mem_s="$(_lzy_jq_or "${run_dir}/score.json" '.scores.memory')"
  disk_s="$(_lzy_jq_or "${run_dir}/score.json" '.scores.disk')"
  net_s="$(_lzy_jq_or "${run_dir}/score.json" '.scores.network')"
  route_s="$(_lzy_jq_or "${run_dir}/score.json" '.scores.route')"
  app_s="$(_lzy_jq_or "${run_dir}/score.json" '.scores.application')"

  local dl ul ping route_guess unlock
  dl="$(_lzy_jq_or "${run_dir}/network.json" '.speedtest.download_mbps')"
  ul="$(_lzy_jq_or "${run_dir}/network.json" '.speedtest.upload_mbps')"
  ping="$(_lzy_jq_or "${run_dir}/network.json" '.speedtest.ping_ms')"
  route_guess="$(_lzy_jq_or "${run_dir}/route.json" '.summary.best_guess')"
  unlock="$(_lzy_jq_or "${run_dir}/streaming.json" '.summary.unlock_score')"

  local cpu_multi mem_read disk_seq
  cpu_multi="$(_lzy_jq_or "${run_dir}/cpu.json" '.sysbench.multi_eps')"
  mem_read="$(_lzy_jq_or "${run_dir}/memory.json" '.read.mib_per_sec')"
  disk_seq="$(_lzy_jq_or "${run_dir}/disk.json" '.sequential.read_mib_s')"

  local nginx_ms redis_ms mysql_ms wp_deploy wp_ttfb
  nginx_ms="$(_lzy_jq_or "${run_dir}/application.json" '.docker.nginx_start_ms')"
  redis_ms="$(_lzy_jq_or "${run_dir}/application.json" '.docker.redis_start_ms')"
  mysql_ms="$(_lzy_jq_or "${run_dir}/application.json" '.docker.mysql_start_ms')"
  wp_deploy="$(_lzy_jq_or "${run_dir}/application.json" '.wordpress.deploy_ms')"
  wp_ttfb="$(_lzy_jq_or "${run_dir}/application.json" '.wordpress.ttfb_ms')"

  local services_rows=""
  if [[ -f "${run_dir}/streaming.json" ]] && lzy_has_jq; then
    services_rows="$(jq -r '.services[]? | "<tr><td>"+.name+"</td><td class=\"st-"+.status+"\">"+.status+"</td><td>"+.detail+"</td></tr>"' \
      "${run_dir}/streaming.json" 2>/dev/null || true)"
  fi

  local generated
  generated="$(lzy_now_iso)"

  cat >"${out}" <<EOF
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>$(_lzy_html_escape "${LZY_NAME}") 评测报告 — $(_lzy_html_escape "${run_id}")</title>
<style>
:root {
  --bg: #0f1419;
  --panel: #1a222c;
  --text: #e8eef4;
  --muted: #8b9aab;
  --accent: #2bb3a3;
  --accent2: #e8a838;
  --line: #2a3542;
  --ok: #3dba7a;
  --no: #e05d5d;
  --unk: #c4a35a;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;
  background:
    radial-gradient(1200px 600px at 10% -10%, #1c3a36 0%, transparent 55%),
    radial-gradient(900px 500px at 100% 0%, #2a2418 0%, transparent 50%),
    var(--bg);
  color: var(--text);
  line-height: 1.55;
}
.wrap { max-width: 960px; margin: 0 auto; padding: 40px 20px 80px; }
.brand {
  font-size: 13px; letter-spacing: 0.18em; text-transform: uppercase;
  color: var(--accent); font-weight: 600; margin-bottom: 8px;
}
h1 { font-size: 2rem; margin: 0 0 8px; font-weight: 700; }
.sub { color: var(--muted); margin-bottom: 28px; }
.hero {
  display: grid; grid-template-columns: 1.2fr 1fr; gap: 20px;
  margin-bottom: 28px;
}
@media (max-width: 720px) { .hero { grid-template-columns: 1fr; } }
.score-box {
  background: linear-gradient(145deg, #1e2c30, var(--panel));
  border: 1px solid var(--line); border-radius: 14px; padding: 28px;
}
.score-num {
  font-size: 4rem; font-weight: 700; color: var(--accent2);
  line-height: 1; margin: 8px 0;
}
.score-box .meta { color: var(--muted); font-size: 0.95rem; }
.info-box {
  background: var(--panel); border: 1px solid var(--line);
  border-radius: 14px; padding: 22px 24px;
}
.info-box dt { color: var(--muted); font-size: 0.8rem; margin-top: 10px; }
.info-box dd { margin: 2px 0 0; font-size: 1.05rem; }
.grid {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  gap: 12px; margin: 18px 0 28px;
}
.card {
  background: var(--panel); border: 1px solid var(--line);
  border-radius: 12px; padding: 16px;
}
.card .label { color: var(--muted); font-size: 0.8rem; }
.card .value { font-size: 1.45rem; font-weight: 650; margin-top: 6px; }
section { margin-top: 32px; }
h2 {
  font-size: 1.15rem; border-bottom: 1px solid var(--line);
  padding-bottom: 8px; margin-bottom: 14px;
}
table { width: 100%; border-collapse: collapse; font-size: 0.95rem; }
th, td { text-align: left; padding: 10px 8px; border-bottom: 1px solid var(--line); }
th { color: var(--muted); font-weight: 600; font-size: 0.8rem; }
.st-yes { color: var(--ok); font-weight: 600; }
.st-no { color: var(--no); font-weight: 600; }
.st-fail, .st-unknown { color: var(--unk); }
.footer { margin-top: 48px; color: var(--muted); font-size: 0.85rem; }
code { background: #12181f; padding: 2px 6px; border-radius: 4px; }
</style>
</head>
<body>
<div class="wrap">
  <div class="brand">$(_lzy_html_escape "${LZY_BRAND}") · $(_lzy_html_escape "${LZY_NAME}")</div>
  <h1>云服务器评测报告</h1>
  <p class="sub">Run ID <code>$(_lzy_html_escape "${run_id}")</code> · 生成于 $(_lzy_html_escape "${generated}") · v$(_lzy_html_escape "${LZY_VERSION}")</p>

  <div class="hero">
    <div class="score-box">
      <div class="meta">综合评分</div>
      <div class="score-num">$(_lzy_html_escape "${overall}")</div>
      <div class="meta">满分 10 · 自动加权标准化</div>
    </div>
    <div class="info-box">
      <dl>
        <dt>主机</dt><dd>$(_lzy_html_escape "${host}")</dd>
        <dt>系统</dt><dd>$(_lzy_html_escape "${os}")</dd>
        <dt>CPU</dt><dd>$(_lzy_html_escape "${cpu_model}")</dd>
        <dt>线路推断</dt><dd>$(_lzy_html_escape "${route_guess}")</dd>
      </dl>
    </div>
  </div>

  <h2>分项评分</h2>
  <div class="grid">
    $(_lzy_html_metric_card "CPU" "${cpu_s}")
    $(_lzy_html_metric_card "Memory" "${mem_s}")
    $(_lzy_html_metric_card "Disk" "${disk_s}")
    $(_lzy_html_metric_card "Network" "${net_s}")
    $(_lzy_html_metric_card "Route" "${route_s}")
    $(_lzy_html_metric_card "Application" "${app_s}")
  </div>

  <h2>关键指标</h2>
  <div class="grid">
    $(_lzy_html_metric_card "CPU 多核 eps" "${cpu_multi}")
    $(_lzy_html_metric_card "内存读 MiB/s" "${mem_read}")
    $(_lzy_html_metric_card "磁盘顺序读" "${disk_seq}")
    $(_lzy_html_metric_card "下行 Mbps" "${dl}")
    $(_lzy_html_metric_card "上行 Mbps" "${ul}")
    $(_lzy_html_metric_card "Ping ms" "${ping}")
    $(_lzy_html_metric_card "解锁分" "${unlock}")
  </div>

  <h2>应用测试</h2>
  <div class="grid">
    $(_lzy_html_metric_card "Nginx 启动 ms" "${nginx_ms}")
    $(_lzy_html_metric_card "Redis 启动 ms" "${redis_ms}")
    $(_lzy_html_metric_card "MySQL 启动 ms" "${mysql_ms}")
    $(_lzy_html_metric_card "WP 部署 ms" "${wp_deploy}")
    $(_lzy_html_metric_card "WP TTFB ms" "${wp_ttfb}")
  </div>

  <section>
    <h2>流媒体 / AI 解锁</h2>
    <table>
      <thead><tr><th>服务</th><th>状态</th><th>详情</th></tr></thead>
      <tbody>
        ${services_rows:-<tr><td colspan="3">无数据</td></tr>}
      </tbody>
    </table>
  </section>

  <p class="footer">
    Generated by $(_lzy_html_escape "${LZY_NAME}") ($(_lzy_html_escape "${LZY_BRAND}")) — Once Test, Multiple Output<br/>
    原始 JSON：<code>$(_lzy_html_escape "${run_dir}")</code>
  </p>
</div>
</body>
</html>
EOF

  lzy_ok "HTML 报告: ${out}"
  printf '%s\n' "${out}"
}

lzy_report_all() {
  local run_dir="${1:-${LZY_RUN_DIR}}"
  lzy_report_markdown "${run_dir}" >/dev/null
  lzy_report_html "${run_dir}" >/dev/null
}
